# [dbo].[TBL_DERSLER]

In [0]:
USE [OkulDB]
GO

In [0]:
/****** Object:  Table [dbo].[TBL_DERSLER]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_DERSLER](
	[DERSID] [int] IDENTITY(1,1) NOT NULL,
	[DERSAD] [varchar](50) NULL,
 CONSTRAINT [PK_TBL_DERSLER] PRIMARY KEY CLUSTERED 
(
	[DERSID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBL_DUYURULAR]

In [0]:
/****** Object:  Table [dbo].[TBL_DUYURULAR]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_DUYURULAR](
	[DUYURUID] [int] IDENTITY(1,1) NOT NULL,
	[DUYURUBASLIK] [varchar](50) NULL,
	[DUYURUICERIK] [varchar](250) NULL,
	[DUYURUOGRT] [int] NULL,
 CONSTRAINT [PK_TBL_DUYURULAR] PRIMARY KEY CLUSTERED 
(
	[DUYURUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBL_MESAJLAR]

In [0]:
/****** Object:  Table [dbo].[TBL_MESAJLAR]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_MESAJLAR](
	[MESAJID] [int] IDENTITY(1,1) NOT NULL,
	[GONDEREN] [varchar](5) NULL,
	[ALICI] [varchar](5) NULL,
	[BASLIK] [varchar](50) NULL,
	[ICERIK] [varchar](500) NULL,
	[TARIH] [smalldatetime] NULL,
 CONSTRAINT [PK_TBL_MESAJLAR] PRIMARY KEY CLUSTERED 
(
	[MESAJID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBL_NOTLAR]

In [0]:
/****** Object:  Table [dbo].[TBL_NOTLAR]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_NOTLAR](
	[NOTID] [int] IDENTITY(1,1) NOT NULL,
	[OGRENCIID] [int] NOT NULL,
	[DERSNotID] [int] NOT NULL,
	[SINAV1] [int] NULL,
	[SINAV2] [int] NULL,
	[SINAV3] [int] NULL,
	[ORTALAMA] [decimal](18, 2) NULL,
	[DURUM] [bit] NULL,
 CONSTRAINT [PK_TBL_NOTLAR] PRIMARY KEY CLUSTERED 
(
	[OGRENCIID] ASC,
	[DERSNotID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBL_OGRENCI]

In [0]:
/****** Object:  Table [dbo].[TBL_OGRENCI]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_OGRENCI](
	[OGRID] [int] IDENTITY(1,1) NOT NULL,
	[NUMARA] [varchar](5) NULL,
	[OGRAD] [varchar](50) NULL,
	[OGRSOYAD] [varchar](50) NULL,
	[OGRFOTOGRAF] [varchar](100) NULL,
	[OGRTELEFON] [varchar](20) NULL,
	[OGRMAIL] [varchar](50) NULL,
	[OGRSIFRE] [varchar](50) NULL,
	[OGRCINSIYET] [varchar](10) NULL,
 CONSTRAINT [PK_TBL_OGRENCI] PRIMARY KEY CLUSTERED 
(
	[OGRID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TBL_OGRETMEN]

In [0]:
/****** Object:  Table [dbo].[TBL_OGRETMEN]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TBL_OGRETMEN](
	[OGRTID] [int] IDENTITY(1,1) NOT NULL,
	[OGRTADSOYAD] [varchar](30) NULL,
	[OGRTFOTO] [varchar](100) NULL,
	[OGRTBRANS] [int] NULL,
	[OGRTNUMARA] [varchar](5) NULL,
	[OGRSIFRE] [varchar](5) NULL,
 CONSTRAINT [PK_TBL_OGRETMEN] PRIMARY KEY CLUSTERED 
(
	[OGRTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [DF_TBL_MESAJLAR_TARIH]

In [0]:
ALTER TABLE [dbo].[TBL_MESAJLAR] ADD  CONSTRAINT [DF_TBL_MESAJLAR_TARIH]  DEFAULT (getdate()) FOR [TARIH]
GO

# [DF_TBL_NOTLAR_SINAV1]

In [0]:
ALTER TABLE [dbo].[TBL_NOTLAR] ADD  CONSTRAINT [DF_TBL_NOTLAR_SINAV1]  DEFAULT ((0)) FOR [SINAV1]
GO

# [DF_TBL_NOTLAR_SINAV2]

In [0]:
ALTER TABLE [dbo].[TBL_NOTLAR] ADD  CONSTRAINT [DF_TBL_NOTLAR_SINAV2]  DEFAULT ((0)) FOR [SINAV2]
GO

# [DF_TBL_NOTLAR_SINAV3]

In [0]:
ALTER TABLE [dbo].[TBL_NOTLAR] ADD  CONSTRAINT [DF_TBL_NOTLAR_SINAV3]  DEFAULT ((0)) FOR [SINAV3]
GO

# [DF_TBL_NOTLAR_ORTALAMA]

In [0]:
ALTER TABLE [dbo].[TBL_NOTLAR] ADD  CONSTRAINT [DF_TBL_NOTLAR_ORTALAMA]  DEFAULT ((0)) FOR [ORTALAMA]
GO

# [DF_TBL_NOTLAR_DURUM]

In [0]:
ALTER TABLE [dbo].[TBL_NOTLAR] ADD  CONSTRAINT [DF_TBL_NOTLAR_DURUM]  DEFAULT ((0)) FOR [DURUM]
GO

# [FK_TBL_DUYURULAR_TBL_OGRETMEN]

In [0]:
ALTER TABLE [dbo].[TBL_DUYURULAR]  WITH CHECK ADD  CONSTRAINT [FK_TBL_DUYURULAR_TBL_OGRETMEN] FOREIGN KEY([DUYURUID])
REFERENCES [dbo].[TBL_OGRETMEN] ([OGRTID])
GO
ALTER TABLE [dbo].[TBL_DUYURULAR] CHECK CONSTRAINT [FK_TBL_DUYURULAR_TBL_OGRETMEN]
GO

# [FK_TBL_DUYURULAR_TBL_OGRETMEN1]

In [0]:
ALTER TABLE [dbo].[TBL_DUYURULAR]  WITH CHECK ADD  CONSTRAINT [FK_TBL_DUYURULAR_TBL_OGRETMEN1] FOREIGN KEY([DUYURUOGRT])
REFERENCES [dbo].[TBL_OGRETMEN] ([OGRTID])
GO
ALTER TABLE [dbo].[TBL_DUYURULAR] CHECK CONSTRAINT [FK_TBL_DUYURULAR_TBL_OGRETMEN1]
GO

# [FK_TBL_NOTLAR_TBL_DERSLER]

In [0]:
ALTER TABLE [dbo].[TBL_NOTLAR]  WITH CHECK ADD  CONSTRAINT [FK_TBL_NOTLAR_TBL_DERSLER] FOREIGN KEY([DERSNotID])
REFERENCES [dbo].[TBL_DERSLER] ([DERSID])
GO
ALTER TABLE [dbo].[TBL_NOTLAR] CHECK CONSTRAINT [FK_TBL_NOTLAR_TBL_DERSLER]
GO

# [FK_TBL_NOTLAR_TBL_OGRENCI]

In [0]:
ALTER TABLE [dbo].[TBL_NOTLAR]  WITH CHECK ADD  CONSTRAINT [FK_TBL_NOTLAR_TBL_OGRENCI] FOREIGN KEY([OGRENCIID])
REFERENCES [dbo].[TBL_OGRENCI] ([OGRID])
GO
ALTER TABLE [dbo].[TBL_NOTLAR] CHECK CONSTRAINT [FK_TBL_NOTLAR_TBL_OGRENCI]
GO

# [FK_TBL_OGRETMEN_TBL_DERSLER]

In [0]:
ALTER TABLE [dbo].[TBL_OGRETMEN]  WITH CHECK ADD  CONSTRAINT [FK_TBL_OGRETMEN_TBL_DERSLER] FOREIGN KEY([OGRTBRANS])
REFERENCES [dbo].[TBL_DERSLER] ([DERSID])
GO
ALTER TABLE [dbo].[TBL_OGRETMEN] CHECK CONSTRAINT [FK_TBL_OGRETMEN_TBL_DERSLER]
GO

# [dbo].[Graf1]

In [0]:
/****** Object:  StoredProcedure [dbo].[Graf1]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[Graf1]
as
Select TBL_DERSLER.DERSAD, Count(*) From TBL_NOTLAR
Inner Join TBL_DERSLER
On TBL_DERSLER.DERSID=TBL_NOTLAR.DERSNotID
Group By TBL_DERSLER.DERSAD
GO

# [dbo].[Graf2]

In [0]:
/****** Object:  StoredProcedure [dbo].[Graf2]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[Graf2]
as
Select OGRCINSIYET, Count(*) From TBL_OGRENCI
Group By OGRCINSIYET
GO

# [dbo].[Graf3]

In [0]:
/****** Object:  StoredProcedure [dbo].[Graf3]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[Graf3]
as
Select OGRCINSIYET, Count(*) From TBL_OGRENCI
Group By TBL_OGRENCI.OGRCINSIYET
GO

# [dbo].[Graf4]

In [0]:
/****** Object:  StoredProcedure [dbo].[Graf4]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[Graf4]
as
Select DERSAD, Count(*) From TBL_DERSLER
inner join TBL_OGRETMEN
on TBL_DERSLER.DERSID = TBL_OGRETMEN.OGRTBRANS
Group By DERSAD
GO

# [dbo].[Graf5]

In [0]:
/****** Object:  StoredProcedure [dbo].[Graf5]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[Graf5]
as
Select (TBL_OGRENCI.OGRAD + ' ' +TBL_OGRENCI.OGRSOYAD) as 'Öğrenci',
Sınav1 From TBL_NOTLAR 
inner join TBL_OGRENCI on TBL_NOTLAR.OGRENCIID = TBL_OGRENCI.OGRID
where DERSNotID = 2
GO

# [dbo].[Graf6]

In [0]:
/****** Object:  StoredProcedure [dbo].[Graf6]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
Create Procedure [dbo].[Graf6]
as
Select (TBL_OGRENCI.OGRAD + ' ' +TBL_OGRENCI.OGRSOYAD) as 'Öğrenci',
Sınav1 From TBL_NOTLAR 
inner join TBL_OGRENCI on TBL_NOTLAR.OGRENCIID = TBL_OGRENCI.OGRID

GO

# [dbo].[OgrNotlar]

In [0]:
/****** Object:  StoredProcedure [dbo].[OgrNotlar]    Script Date: 6.06.2021 23:44:20 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE Procedure [dbo].[OgrNotlar]
As
Select NOTID, OGRENCIID, (OGRAD +' '+ OGRSOYAD) AS 'OGRENCIADSOYAD',OGRENCIID, DERSAD, SINAV1, SINAV2, SINAV3, ORTALAMA, DURUM From TBL_NOTLAR
INNER JOIN  TBL_OGRENCI
ON TBL_OGRENCI.OGRID=TBL_NOTLAR.OGRENCIID
INNER JOIN TBL_DERSLER
ON TBL_DERSLER.DERSID=TBL_NOTLAR.DERSNotID
GO